const mongoose = require('mongoose');
const Schema = mongoose.Schema;

/*
 * Generated by: Mongoose Schema Designer
 * At: 12 december 2019
 * Author: Marc de Hoogh
 */
const RecipeSchema = new Schema({
  // TODO: write the schema
  title:{type:mongoose.Schema.Types.String,unique:true,required:true},
  level:{type:mongoose.Schema.Types.String,enum:["Easy Peasy","Amateur Chef","UltraPro Chef"]},
  ingredients:[mongoose.Schema.Types.String],
  cuisine:{type:mongoose.Schema.Types.String,required:true},
  dishType:{type:mongoose.Schema.Types.String,enum:["Breakfast","Dish","Snack","Drink","Dessert","Other"]},
  image:{type:mongoose.Schema.Types.String,default:'https://images.media-allrecipes.com/images/75131.jpg'},
  duration:{type:mongoose.Schema.Types.Number,min:0.0},
  creator:mongoose.Schema.Types.String,
  created:mongoose.Schema.Types.Date,
});

const Recipe = mongoose.model('Recipe', RecipeSchema);
module.exports = Recipe;